export const estados = [
    { Nome: "Acre", Sigla: "AC" },
    { Nome: "Alagoas", Sigla: "AL" },
    { Nome: "Amapá", Sigla: "AP" },
    { Nome: "Amazonas", Sigla: "AM" },
    { Nome: "Bahia", Sigla: "BA" },
    { Nome: "Ceará", Sigla: "CE" },
    { Nome: "Distrito Federal", Sigla: "DF" },
    { Nome: "Espírito Santos", Sigla: "ES" },
    { Nome: "Goiás", Sigla: "GO" },
    { Nome: "Maranhão", Sigla: "MA" },
    { Nome: "Mato Grosso", Sigla: "MT" },
    { Nome: "Mato Grosso do Sul", Sigla: "MS" },
    { Nome: "Minas Gerais", Sigla: "MG" },
    { Nome: "Pará", Sigla: "PA" },
    { Nome: "Paraíba", Sigla: "PB" },
    { Nome: "Paraná", Sigla: "PR" },
    { Nome: "Pernambuco", Sigla: "PE" },
    { Nome: "Piauí", Sigla: "PI" },
    { Nome: "Rio de Janeiro", Sigla: "RJ" },
    { Nome: "Rio Grande do Norte", Sigla: "RN" },
    { Nome: "Rio Grande do Sul", Sigla: "RS" },
    { Nome: "Rondônia", Sigla: "RO" },
    { Nome: "Roraima", Sigla: "RR" },
    { Nome: "Santa Catarina", Sigla: "SC" },
    { Nome: "Sao Paulo", Sigla: "SP" },
    { Nome: "Sergipe", Sigla: "SE" },
    { Nome: "Tocantins", Sigla: "TO" },
]